Small things
rabbitmq/messaging-topology-operator pull request #232
Opened 2021-09-10 08:47 UTC by ChunyiLyu

This closes #

**Note to reviewers:** remember to look at the commits in this PR and consider if they can be squashed
**Note to contributors:** remember to re-generate client set if there are any API changes

## Summary Of Changes

Small refactors; see commit messages

## Additional Context

2021-09-10 09:07 UTC, ansd requested changes

2021-09-10 09:07 UTC, ansd commented on internal/cluster_reference_test.go
>  				Expect(err.Error()).To(ContainSubstring("no status.binding set"))
Let's combine these two expectations using the `MatchError` matcher.

2021-09-10 09:07 UTC, ansd commented on internal/cluster_reference_test.go
> +				Expect(err).To(HaveOccurred())
Let's combine these two expectations using the `MatchError` matcher.

2021-09-10 10:22 UTC, ansd approved these changes

2021-09-13 11:37 UTC, Zerpet approved these changes

2021-09-14 08:32 UTC, merged