Temporary fix on deletion_system_test in order to avoid to create a m…
rabbitmq/messaging-topology-operator pull request #350
Opened 2022-04-14 08:48 UTC by DanielePalaia

…irror queue in a one pod cluster causing the pod to get stuck in "terminating" phase and preventing our pipeline to work.

It can be reverted once await_online_synchronized_mirror get fixed to manage this case

This closes #

**Note to reviewers:** remember to look at the commits in this PR and consider if they can be squashed
**Note to contributors:** remember to re-generate client set if there are any API changes

## Summary Of Changes

## Additional Context

2022-04-20 10:10 UTC, coro approved these changes

2022-04-20 11:36 UTC, Zerpet requested changes
I'd much rather mark the test as "skip" than giving us a false sense of successful test.

I think the test has caught a legitimate bug, in the Core in this case. If we want to make the pipeline green, we should just skip this test.

2022-04-21 16:13 UTC, DanielePalaia commented
No, that's of course fine! Done!

2022-04-21 16:18 UTC, Zerpet approved these changes
Ship it!

2022-04-21 16:24 UTC, merged