Rename ValidatingWebhookConfiguration to avoid conflicts from other c…
rabbitmq/messaging-topology-operator pull request #389
Opened 2022-06-07 19:18 UTC by evankanderson

**Note to reviewers:** remember to look at the commits in this PR and consider if they can be squashed
**Note to contributors:** remember to re-generate client set if there are any API changes

## Summary Of Changes

- Change kustomization for webhook so that the generated webhook doesn't collide with webhooks for other projects. This was noticed as a conflict with `cartographer`, but could happen with _any_ other Kubernetes controller based on controller-runtime.
- Note that this doesn't change the Service name for the webhook, because the Service is namespaced, and so won't collide with other components installed in the cluster. The ValidatingWebhookConfiguration is cluster-scoped, so the namespace collision is more of a concern (particularly since `controller-gen` generates that name by default).

## Additional Context

- You probably need some install instructions about how to clean up the existing webhook; this seems worth it given the likelihood of future collisions.

2022-06-08 09:53 UTC, ChunyiLyu commented
Correction from the previous comment https://github.com/rabbitmq/messaging-topology-operator/pull/388#issuecomment-1148399908

Patch is correctly applied with `make generate-manifests` and other deploy make targets. As for the svc, the team could  update webhook service name in a different PR.

2022-06-08 09:58 UTC, Zerpet requested changes
Hey there 👋 Thank you for the contribution! I'm not sure what's up with the CLA bot, but given your commit is signed with a VMware email, I'm happy to just merge this this PR when it's ready. 
On that front, I have a change to request regarding the commit message. The subject line of your commit message is longer than 50 characters, which does not adhere to our [contribution guidelines](https://github.com/rabbitmq/messaging-topology-operator/blob/main/CONTRIBUTING.md#pull-requests), specifically: _commit with a [descriptive message](https://cbea.ms/git-commit/#seven-rules)_.

I'll be happy to merge this once you amend the commit to adhere to the guidelines. Thank you!

2022-06-16 22:19 UTC, evankanderson commented
Sorry for the delay, I was out for a bit.

I removed the justification part of the change from the first line, leaving only the description of what changed.

2022-06-17 11:06 UTC, Zerpet approved these changes
Thank you!

2022-06-17 11:06 UTC, merged